# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'MIIBNI4Push' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MIIBNI4Push
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
